api_key: KEY_FROM_MPDS
api_mp: KEY_FROM_MP
mp_path: PATH_TO_FOLDER_MP_DATA
mpds_path: PATH_TO_FOLDER_MPDS_DATA
processed_path: PATH_TO_SAVE
raw_mpds: PATH_WITH_MPDS_RAW_DATA
raw_polyhedra_path: PATH_TO_RAW_POLY
polyhedra_path: PATH_TO_PROCESSED_POLY
scaler_path: PATH_TO_SCALERS
weights: PATH_TO_WEIGHTS